;;; console light --- theme
;;; Commentary:
;;; Code:

(load-file "~/.emacs.d/theme_variables.el")

(setq background-diff-added "darkseagreen1")
(setq background-diff-added-highlight "seagreen1")
(setq background-diff-current-A "lightpink1")
(setq background-diff-current-Ancestor "gray86")
(setq background-diff-current-B "darkseagreen1")
(setq background-diff-current-C "lightgoldenrod1")
(setq background-diff-even-A "gray86")
(setq background-diff-even-Ancestor "gray86")
(setq background-diff-even-B "gray86")
(setq background-diff-even-C "gray86")
(setq background-diff-fine-A "palevioletred1")
(setq background-diff-fine-Ancestor "gray86")
(setq background-diff-fine-B "seagreen1")
(setq background-diff-fine-C "khaki1")
(setq background-diff-odd-A "gray86")
(setq background-diff-odd-Ancestor "gray86")
(setq background-diff-odd-B "gray86")
(setq background-diff-odd-C "gray86")
(setq background-diff-removed "lightpink1")
(setq background-diff-removed-highlight "palevioletred1")
(setq background "#ffffff")
(setq background-fringe "ivory2")
(setq background-hl "azure2")
(setq background-magit "ivory2")
(setq background-magit-dark "gray95")
(setq background-mode-line "gray80")
(setq background-region "moccasin")
(setq text-comment "cornflowerblue")
(setq text-constant "black")
(setq text-function "black")
(setq text-highlight-1 "mediumblue")
(setq text-highlight-2 "deeppink4")
(setq text-highlight-3 "deeppink3")
(setq text-info "darkorange3")
(setq text-keyword "deeppink4")
(setq text-line-number "gray60")
(setq text-low "royalblue")
(setq text-lower "gray60")
(setq text-mode-line "darkmagenta")
(setq text-normal "black")
(setq text-preprocessor "gray68")
(setq text-type "deeppink4")
(setq text-variable "mediumblue")
(setq text-whitespace "gray68")

;;; theme_console_light.el ends here
