;;; console dark --- theme
;;; Commentary:
;;; Code:

(load-file "~/.emacs.d/theme_variables.el")

(setq background-diff-added "#698b69")
(setq background-diff-added-highlight "#008b45")
(setq background-diff-current-A "#ffaeb9")
(setq background-diff-current-Ancestor "#dbdbdb")
(setq background-diff-current-B "#c1ffc1")
(setq background-diff-current-C "#ffec8b")
(setq background-diff-even-A "#dbdbdb")
(setq background-diff-even-Ancestor "#dbdbdb")
(setq background-diff-even-B "#dbdbdb")
(setq background-diff-even-C "#dbdbdb")
(setq background-diff-fine-A "#ff82ab")
(setq background-diff-fine-Ancestor "#dbdbdb")
(setq background-diff-fine-B "#c1ffc1")
(setq background-diff-fine-C "#fff68f")
(setq background-diff-odd-A "#dbdbdb")
(setq background-diff-odd-Ancestor "#dbdbdb")
(setq background-diff-odd-B "#dbdbdb")
(setq background-diff-odd-C "#dbdbdb")
(setq background-diff-removed "#8b3a3a")
(setq background-diff-removed-highlight "#cd3333")
(setq background "#000000")
(setq background-fringe "#242424")
(setq background-hl "#000080")
(setq background-magit "#000000")
(setq background-magit-dark "#000000")
(setq background-mode-line "#000000")
(setq background-region "#8b1a1a")
(setq text-comment "#ffe7ba")
(setq text-constant "#ffe7ba")
(setq text-function "#ffe7ba")
(setq text-highlight-1 "#00ff7f")
(setq text-highlight-2 "#7fff00")
(setq text-highlight-3 "#ffc125")
(setq text-info "#ffe7ba")
(setq text-keyword "#cdba96")
(setq text-line-number "#cdba96")
(setq text-low "#eed8ae")
(setq text-lower "#cdba96")
(setq text-mode-line "#ffe7ba")
(setq text-normal "#ffe7ba")
(setq text-preprocessor "#ffe7ba")
(setq text-type "#8b7e66")
(setq text-variable "#ffe7ba")
(setq text-whitespace "#8b7e66")

;;; theme_console_dark.el ends here
