;;; theme_default_dark --- common dark theme
;;; Commentary:
;;; Code:

(load-file "~/.emacs.d/theme_variables.el")

(defvar alert-1)
(defvar alert-2)
(defvar alert-3)
(defvar background-buffer-id-projectile)
(defvar background-current-diff-A)
(defvar background-current-diff-B)
(defvar background-current-diff-C)
(defvar background-cursor)
(defvar background-diff-added)
(defvar background-diff-added-highlight)
(defvar background-diff-removed)
(defvar background-diff-removed-highlight)
(defvar background-ediff)
(defvar background-fine-diff-A)
(defvar background-fine-diff-B)
(defvar background-fine-diff-C)
(defvar background-magit-branch-local)
(defvar background-magit-branch-remote)
(defvar background-match)
(defvar blue-1)
(defvar blue-2)
(defvar evil-emacs-1)
(defvar evil-emacs-2)
(defvar evil-insert-1)
(defvar evil-insert-2)
(defvar evil-motion-1)
(defvar evil-motion-2)
(defvar evil-normal-1)
(defvar evil-normal-2)
(defvar evil-operator-1)
(defvar evil-operator-2)
(defvar evil-replace-1)
(defvar evil-replace-1)
(defvar evil-replace-2)
(defvar evil-replace-2)
(defvar evil-visual-1)
(defvar evil-visual-2)
(defvar gray-1)
(defvar gray-2)
(defvar green-1)
(defvar green-2)
(defvar ivy-background)
(defvar ivy-text)
(defvar orange-1)
(defvar orange-2)
(defvar red-1)
(defvar red-2)
(defvar text-buffer-id)
(defvar text-constant)
(defvar text-diff-added)
(defvar text-diff-removed)
(defvar text-ediff)
(defvar text-error)
(defvar text-function)
(defvar text-keyword)
(defvar text-magit-branch-local)
(defvar text-magit-branch-remote)
(defvar text-match)
(defvar text-mode-line)
(defvar text-mode-line-border)
(defvar text-preprocessor)
(defvar text-type)
(defvar text-variable)
(defvar text-warning)
(defvar violet-1)
(defvar violet-2)
(defvar yellow-1)
(defvar yellow-2)
(setq alert-1 "#ee6666")
(setq alert-2 "#aa6666")
(setq alert-3 "#555555")
(setq background-buffer-id-projectile "#2a1f00")
(setq background-current-diff-A "#e83434")
(setq background-current-diff-B "#62ac48")
(setq background-current-diff-C "#bcaa31")
(setq background-cursor "#00ff00")
(setq background-diff-added "#386329")
(setq background-diff-added-highlight "#62ac48")
(setq background-diff-removed "#a32424")
(setq background-diff-removed-highlight "#e83434")
(setq background-ediff "#888888")
(setq background-fine-diff-A "#fc6c6c")
(setq background-fine-diff-B "#82c36b")
(setq background-fine-diff-C "#e0ca3b")
(setq background-magit-branch-local "#003300")
(setq background-magit-branch-remote "#330000")
(setq background-match "#43006d")
(setq blue-1 "#1e90ff")
(setq blue-2 "#202055")
(setq evil-emacs-1 "#f974f9")
(setq evil-emacs-2 "#43006d")
(setq evil-insert-1 "#ffb9b9")
(setq evil-insert-2 "#850d0d")
(setq evil-motion-1 "#1e90ff")
(setq evil-motion-2 "#202055")
(setq evil-normal-1 "#1ad600")
(setq evil-normal-2 "#004400")
(setq evil-operator-1 "#1e90ff")
(setq evil-operator-2 "#202055")
(setq evil-replace-1 "#ff7f00")
(setq evil-replace-1 "#ffb9b9")
(setq evil-replace-2 "#4e2700")
(setq evil-replace-2 "#850d0d")
(setq evil-visual-1 "#d6b400")
(setq evil-visual-2 "#554804")
(setq gray-1 "#999999")
(setq gray-2 "#444444")
(setq green-1 "#1ad600")
(setq green-2 "#004400")
(setq ivy-background "#2a1f00")
(setq ivy-text "#ffff00")
(setq orange-1 "#ff7f00")
(setq orange-2 "#4e2700")
(setq red-1 "#e52222")
(setq red-2 "#6b0a0a")
(setq text-constant "#cb6a30")
(setq text-diff-added "#000000")
(setq text-diff-removed "#000000")
(setq text-ediff "#000000")
(setq text-error "#ffff00")
(setq text-function "#109800")
(setq text-keyword "#d091ff")
(setq text-magit-branch-local "#00bb00")
(setq text-magit-branch-remote "#bb0000")
(setq text-match "#f974f9")
(setq text-mode-line "#ffff00")
(setq text-mode-line-border "#838300")
(setq text-preprocessor "#04bcc0")
(setq text-type "#bb4f80")
(setq text-variable "#7ea0f7")
(setq text-warning "#ff0000")
(setq violet-1 "#f974f9")
(setq violet-2 "#43006d")
(setq yellow-1 "#d6b400")
(setq yellow-2 "#554804")

;;; theme_default_dark.el ends here
