;;; yellow --- theme
;;; Commentary:
;;; Code:

(load-file "~/.emacs.d/theme_variables.el")

(setq background-1 "#ffec8b")
(setq background-2 "#ddcc00")
(setq background-3 "#bbaa00")
(setq background-4 "#ddca69")
(setq background-5 "#ffec8b")
(setq background-fringe "#ddca69")
(setq background-hl "#ddca69")
(setq background-magit "#ddca69")
(setq background-magit-dark "#bba847")
(setq background-match "#ffff00")
(setq background-mode-line "#ddca69")
(setq background-mode-line-active "#ddca69")
(setq font-lock-blue "#ffec8b")
(setq font-lock-green "#ffec8b")
(setq font-lock-red "#ffec8b")
(setq line-number-1 "#bbaa00")
(setq line-number-2 "#ffec8b")
(setq line-number-3 "#bbaa00")
(setq line-number-4 "#ffec8b")
(setq text-constant "#0000c0")
(setq text-function "#ee7700")
(setq text-highlight-1 "#ff0000")
(setq text-highlight-2 "#897700")
(setq text-hl "#000000")
(setq text-keyword "#dd9900")
(setq text-low "#bbaa00")
(setq text-lower "#ddca69")
(setq text-match "#000000")
(setq text-normal "#000000")
(setq text-preprocessor "#afafaf")
(setq text-type "#aaaa00")
(setq text-variable "#6a3e3e")
(setq text-warning "#6a3e3e")

;;; theme_yellow.el ends here
