;;; theme_default_light --- common light theme
;;; Commentary:
;;; Code:

(load-file "~/.emacs.d/theme_variables.el")

(setq alert-1 "#ff0000")
(setq alert-2 "#ee9966")
(setq alert-3 "#cccccc")
(setq background-buffer-id-projectile "#ffff00")
(setq background-current-diff-A "#ffdddd")
(setq background-current-diff-B "#ddffdd")
(setq background-current-diff-C "#ffffaa")
(setq background-cursor "#ff0000")
(setq background-diff-added "#ddffdd")
(setq background-diff-added-highlight "#cceecc")
(setq background-diff-removed "#ffdddd")
(setq background-diff-removed-highlight "#eecccc")
(setq background-ediff "#dddddd")
(setq background-fine-diff-A "#ffbbbb")
(setq background-fine-diff-B "#aaffaa")
(setq background-fine-diff-C "#ffff55")
(setq background-magit-branch-local "#00de00")
(setq background-magit-branch-remote "#ff2f2f")
(setq background-match "#ffe2ff")
(setq color-blue-1 "#1111ca")
(setq color-blue-2 "#bcdfff")
(setq color-gray-1 "#333333")
(setq color-gray-2 "#dddddd")
(setq color-green-1 "#113e00")
(setq color-green-2 "#d6ffc7")
(setq color-orange-1 "#7b2d06")
(setq color-orange-2 "#ffce82")
(setq color-red-1 "#850b0b")
(setq color-red-2 "#ffc8c8")
(setq color-violet-1 "#611481")
(setq color-violet-2 "#f0cdff")
(setq color-yellow-1 "#645900")
(setq color-yellow-2 "#fff190")
(setq evil-emacs-1 "#611481")
(setq evil-emacs-2 "#f0cdff")
(setq evil-insert-1 "#850b0b")
(setq evil-insert-2 "#ffc8c8")
(setq evil-motion-1 "#1111ca")
(setq evil-motion-2 "#bcdfff")
(setq evil-normal-1 "#113e00")
(setq evil-normal-2 "#d6ffc7")
(setq evil-operator-1 "#1111ca")
(setq evil-operator-2 "#bcdfff")
(setq evil-replace-1 "#7b2d06")
(setq evil-replace-1 "#d6ffc7")
(setq evil-replace-2 "#850b0b")
(setq evil-replace-2 "#ffce82")
(setq evil-visual-1 "#645900")
(setq evil-visual-2 "#fff190")
(setq text-constant "#994410")
(setq text-cursor "#000000")
(setq text-diff-added "#22aa22")
(setq text-diff-removed "#aa2222")
(setq text-ediff "#000000")
(setq text-error "#ff0000")
(setq text-error "#ff0000")
(setq text-function "#258800")
(setq text-info "#000000")
(setq text-keyword "#af06d0")
(setq text-magit-branch-local "#000000")
(setq text-magit-branch-remote "#000000")
(setq text-match "#9b209b")
(setq text-mode-line "#000000")
(setq text-mode-line-border "#000000")
(setq text-preprocessor "#04bcc0")
(setq text-type "#bb0606")
(setq text-variable "#0e4ae5")
(setq text-warning "#ff9900")

;;; theme_default_light.el ends here
