;;; console light --- theme
;;; Commentary:
;;; Code:

(load-file "~/.emacs.d/theme_variables.el")

(setq background-diff-added "darkseagreen1")
(setq background-diff-added-highlight "seagreen1")
(setq background-diff-current-A "#ffdddd")
(setq background-diff-current-Ancestor "#dddddd")
(setq background-diff-current-B "#ddffdd")
(setq background-diff-current-C "#ffffaa")
(setq background-diff-even-A "#bbbbbb")
(setq background-diff-even-Ancestor "#bbbbbb")
(setq background-diff-even-B "#bbbbbb")
(setq background-diff-even-C "#bbbbbb")
(setq background-diff-fine-A "#ffbbbb")
(setq background-diff-fine-Ancestor "#dddddd")
(setq background-diff-fine-B "#aaffaa")
(setq background-diff-fine-C "#ffff55")
(setq background-diff-odd-A "#dddddd")
(setq background-diff-odd-Ancestor "#dddddd")
(setq background-diff-odd-B "#dddddd")
(setq background-diff-odd-C "#dddddd")
(setq background-diff-removed "lightpink1")
(setq background-diff-removed-highlight "palevioletred1")
(setq background "brightwhite")
(setq background-fringe "ivory2")
(setq background-hl "azure2")
(setq background-magit "ivory2")
(setq background-magit-dark "gray95")
(setq background-mode-line "gray80")
(setq background-region "moccasin")
(setq text-comment "cornflowerblue")
(setq text-constant "black")
(setq text-function "black")
(setq text-highlight-1 "mediumblue")
(setq text-highlight-2 "deeppink4")
(setq text-highlight-3 "deeppink3")
(setq text-info "darkorange3")
(setq text-keyword "deeppink4")
(setq text-line-number "gray60")
(setq text-low "royalblue")
(setq text-lower "gray60")
(setq text-mode-line "darkmagenta")
(setq text-normal "black")
(setq text-preprocessor "gray68")
(setq text-type "deeppink4")
(setq text-variable "mediumblue")
(setq text-whitespace "gray68")

;;; theme_console_light.el ends here
